<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Shared test infrastructure for Less3</Description>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.102.1" />
    <PackageReference Include="Touchstone.Core" Version="0.1.12" />
    <ProjectReference Include="..\..\src\Less3\Less3.csproj" />
  </ItemGroup>

</Project>
