<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>NUnit adapter tests for Less3 Touchstone descriptors</Description>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Test.Shared\Test.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="NUnit" Version="4.3.2" />
    <PackageReference Include="NUnit.Analyzers" Version="4.7.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
    <PackageReference Include="Touchstone.NunitAdapter" Version="0.1.12" />
  </ItemGroup>

</Project>
